name: Deploy new release

on:
  release:
	  types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    - name: Pull latest release from GitHub
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ~/quinn
          git pull git@github.com:unreal-slackrs/quinn.git
    - name: Build & run
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ~/quinn
          npm ci
          TOKEN=${{ secrets.TOKEN }}
          GUILD=${{ secrets.GUILD }}
          pm2 reload quinn
